### ISSUE TITLE
触控按键无效果，除了潜行

### ISSUE THREAD

**Issue by ShulkerSakura** [TouchController/TouchController#1]
在官方版FCL中安装了TouchController，提示未连接到代理，TouchController禁用，但是触控按键可以使用，不能移动视角，使用TouchController构建的FCL安装TouchController，不提示未连接的代理，但是触控按键和视角移动均不能工作。

**Comment by WhiteElephant-abc** [comment]
现在应该已经解决了吧，这个issues是不是忘关了
