### ISSUE TITLE
按住前进无法上浮

### ISSUE THREAD

**Issue by WhiteElephant-abc** [TouchController/TouchController#109]
在国际基岩版1.21.51.02中，游泳时抬头或低头即可上浮/下潜，而TC中只会下沉

**Comment by fifth-light** [comment]
> 游泳时抬头或低头即可上浮/下潜

我使用 mod 测试时，抬头向前游泳可以向上游，具体来说基岩版是怎样的行为？

**Comment by fengzhou0w0** [comment]
个人测试了java版和基岩版1.21，机制基本一致，游泳状态的运动方向，只会朝视线的正前方。水中行走状态无论视角朝向哪里，都不会上浮只会下沉。

**Comment by WhiteElephant-abc** [comment]
> > 游泳时抬头或低头即可上浮/下潜
> 
> 我使用 mod 测试时，抬头向前游泳（疾跑）可以向上游，具体来说基岩版是怎样的行为？

只拖动摇杆，不碰上下，拖动屏幕，便可向上或向下游泳

**Comment by fifth-light** [comment]
@WhiteElephant-abc  你不会把“使用摇杆冲刺”打开了吧？我打开这个选项确实可以向上下游泳（毕竟游泳就是水中疾跑），但是不打开是不行的。

**Comment by WhiteElephant-abc** [comment]
#98 
> > > 即将摇杆拖到顶触发疾跑
> > 
> > 
> > 你说的是“使用摇杆冲刺”这个选项吧
> 
> 是基岩版的选项吗？我反正在基岩版里可以这么疾跑，可能之前我开过这个选项


可能是吧

**Comment by WhiteElephant-abc** [comment]
> @WhiteElephant-abc 你不会把“使用摇杆冲刺”打开了吧？我打开这个选项确实可以向上下游泳（毕竟游泳就是水中疾跑），但是不打开是不行的。

那就合并到 #98 ？

**Comment by WhiteElephant-abc** [comment]
> @WhiteElephant-abc 你不会把“使用摇杆冲刺”打开了吧？我打开这个选项确实可以向上下游泳（毕竟游泳就是水中疾跑），但是不打开是不行的。

那么java版疾跑抬头也可以向上游是吗

**Comment by fifth-light** [comment]
> 那么java版疾跑抬头也可以向上游是吗

是的
