### ISSUE TITLE
无法与实体交互

### ISSUE THREAD

**Issue by Handsomeprin** [TouchController/TouchController#27]
![Uploading Screenshot_20241214_204135.jpg…]()

**Comment by UNKNOWPLR** [comment]
> 你用的是什么版本的 TouchController 这个问题已经在 commit [be6a497](https://github.com/fifth-light/TouchController/commit/be6a497c202783e005a15527e18741a3af9a1d7c) #16 修复 发布于 [v0.0.7](https://github.com/fifth-light/TouchController/releases/tag/v0.0.7)

0.0.6
