### ISSUE TITLE
自定义中锚点不便切换

### ISSUE THREAD

**Issue by WhiteElephant-abc** [TouchController/TouchController#47]
每次都需要点好几下  希望可以直接选择某一种锚点

**Comment by fengzhou0w0** [comment]
我认为按钮修改界面，还是做成全屏的效果更为直观，添加按钮和修改按钮的菜单就改成悬浮窗模式更好。

**Comment by fifth-light** [comment]
合并到 #26

**Comment by fifth-light** [comment]
![目前的进度](https://github.com/user-attachments/assets/90910462-0b93-40b8-b2b8-d1b3374aa03d)
目前的进度
