### ISSUE TITLE
设置时容易误触

### ISSUE THREAD

**Issue by WhiteElephant-abc** [TouchController/TouchController#50]
例如添加控件以及在物品设置中添加物品
这些操作都只需点击一下，容易误触，而撤销这些操作需要两下而且还不是像误触一样可以点任意地方

配合 #40 会导致误触造成更大困扰

**Comment by WhiteElephant-abc** [comment]
就比如添加控件就可以点击后弹窗确认，弹窗中还可以设置大小，这样也不用显得弹窗麻烦

**Comment by fifth-light** [comment]
合并到 #26
