### ISSUE TITLE
添加 Esc 按键

### ISSUE THREAD

**Issue by KremeCN** [TouchController/TouchController#71]
在 Windows 下，不能用 Pojav/FCL 的按键映射，因为没有 Esc 键无法脱离键盘使用。希望加入 Esc 键，乃至于自定义其他按键。

**Comment by fengzhou0w0** [comment]
你的意思其实是想说，在Windows下，没有退出背包界面或者工作台界面的图形选项，只能通过使用外接键盘上的esc键，才能回到游戏对吧。

**Comment by fengzhou0w0** [comment]
这个问题还有个解决思路，Windows上应该也有其他的软件，可以实现类似安卓端启动器的图形化按键映射的功能吧。

**Comment by fifth-light** [comment]
与 #25 重复
