### ISSUE TITLE
拖动手指不能按下其他按键

### ISSUE THREAD

**Issue by WhiteElephant-abc** [TouchController/TouchController#99]
参照 #65，飞行时，手指从上升拖动到下降，并不会按下下降

**Comment by WhiteElephant-abc** [comment]
实测在国际基岩版1.21.51.02中，移开手指，手指会变成拖动屏幕（及移开后，手指下出现圆圈）

**Comment by fifth-light** [comment]
> 手指从上升拖动到下降，并不会按下下降

刚在 commit 31b1ec9ae494daeb79ea6f613de1960c6f2610b4 改了改，下载最新构建试试？

**Comment by fifth-light** [comment]
> 移开手指，手指会变成拖动屏幕

这一点我有测试过，的确是这样。要实现这一点得大改 SwipeButton 和 Button 的逻辑了。

**Comment by WhiteElephant-abc** [comment]
> > 移开手指，手指会变成拖动屏幕
> 
> 这一点我有测试过，的确是这样。要实现这一点得大改 SwipeButton 和 Button 的逻辑了。

拖动可以按下下降和拖动变成拖动屏幕这两点是冲突的，如果实现了拖动按下下降（或其他按键），那就够了
